name: ${project.name}
main: net.daboross.bukkitdev.bouncysnow.BouncySnow
version: ${project.version}
author: Dabo Ross
description: Makes you bounce on snow
commands:
  reloadbouncysnow:
    description: Reloads the Bouncy Snow configuration
    permission: bouncysnow.reload
